version: "3.8"
services:
  go-backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  python-backend:
    build:
      context: ./Backend/Database
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - cockroachdb

  react-frontend:
    build:
      context: ./Frontend/zwift
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_GO_BACKEND_URL=http://go-backend:3001
      - REACT_APP_PYTHON_BACKEND_URL=http://python-backend:8000

  cockroachdb:
    image: cockroachdb/cockroach:v21.1.7
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - type: volume
        source: cockroachdb_data
        target: /cockroach/cockroach-data

volumes:
  cockroachdb_data:
