version: "3.8"
services:
  go-backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8085:8085"  # Expose Go backend on port 8080

  cockroachdb:
    image: cockroachdb/cockroach:v21.1.7
    command: start-single-node --insecure --listen-addr=0.0.0.0:26257
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - type: volume
        source: cockroachdb_data
        target: /cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  python-backend:
    build:
      context: ./Backend/Database
      dockerfile: Dockerfile
    environment:
      - DB_HOST=cockroachdb  # Use the service name as the database host
    ports:
      - "8000:8000"  # Expose Python backend on port 8000
    depends_on:
      cockroachdb:
        condition: service_healthy
    command: sh -c "sleep 10 && /code/entrypoint.sh"

  react-frontend:
    build:
      context: ./Frontend/zwift
      dockerfile: Dockerfile
      args:
        REACT_APP_GO_BACKEND_URL: http://34.32.62.23:8085
        REACT_APP_PYTHON_BACKEND_URL: http://34.32.62.23:8000
        REACT_APP_FRONTEND_URL: http://34.32.62.23
    ports:
      - "80:80"  # Expose React frontend on port 80

volumes:
  cockroachdb_data: