version: "3.8"
services:
  go-backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Expose Go backend on port 8080

  cockroachdb:
    image: cockroachdb/cockroach:v21.1.7
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - type: volume
        source: cockroachdb_data
        target: /cockroach/cockroach-data

  python-backend:
    build:
      context: ./Backend/Database
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose Python backend on port 8000
    depends_on:
      - cockroachdb

  react-frontend:
    build:
      context: ./Frontend/zwift
      dockerfile: Dockerfile
      args:
        REACT_APP_GO_BACKEND_URL: http://34.32.62.23:8080
        REACT_APP_PYTHON_BACKEND_URL: http://34.32.62.23:8000
    ports:
      - "80:80"  # Expose React frontend on port 80

volumes:
  cockroachdb_data:
